export type Theme = {
    name: string;
    emoji: string;
};

export const supportedThemeNames = [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
];

export const supportedThemes: Theme[] = [
    { name: "light", emoji: "🌕" },
    { name: "dark", emoji: "🌑" },
    { name: "cupcake", emoji: "🧁" },
    { name: "bumblebee", emoji: "🐝" },
    { name: "emerald", emoji: "✳️" },
    { name: "corporate", emoji: "🏢" },
    { name: "synthwave", emoji: "🌆" },
    { name: "retro", emoji: "📺" },
    { name: "cyberpunk", emoji: "🤖" },
    { name: "valentine", emoji: "💖" },
    { name: "halloween", emoji: "🎃" },
    { name: "garden", emoji: "🌷" },
    { name: "forest", emoji: "🌲" },
    { name: "aqua", emoji: "🐟" },
    { name: "lofi", emoji: "📼" },
    { name: "pastel", emoji: "🎨" },
    { name: "fantasy", emoji: "🧝" },
    { name: "wireframe", emoji: "📝" },
    { name: "black", emoji: "⚫" },
    { name: "luxury", emoji: "💎" },
    { name: "dracula", emoji: "🧛" },
    { name: "cmyk", emoji: "🎨" },
    { name: "autumn", emoji: "🍂" },
    { name: "business", emoji: "🏢" },
    { name: "acid", emoji: "🧪" },
    { name: "lemonade", emoji: "🍋" },
    { name: "night", emoji: "🌙" },
    { name: "coffee", emoji: "☕" },
    { name: "winter", emoji: "⛄" },
    { name: "dim", emoji: "🌒" },
    { name: "nord", emoji: "❄️" },
    { name: "sunset", emoji: "🌇" },
];
